mod one;
mod two;
mod three;
mod four;
mod five;
mod six;
mod new_seven;
mod eight;
mod nine;
mod ten;
mod eleven;
mod twelve;
mod thirteen;
mod fourteen;
mod fifteen;

fn main() {
    println!("{:?}", fifteen::fifteen());
    //println!("{:?}", fourteen::fourteen());
    //println!("{:?}", thirteen::thirteen());
    //println!("{:?}", twelve::twelve());
    //println!("{:?}", eleven::eleven());
    //println!("{:?}", ten::ten());
    //println!("{:?}", nine::nine());
    //println!("{:?}", eight::eight());
    //println!("{:?}", new_seven::seven_p1());
    //println!("{:?}", six::six_p2());
    //println!("{:?}", six::six_p1());
    //println!("{:?}", five::five_p2());
    //println!("{:?}", five::five_p1());
    //println!("{:?}", four::four_p2());
    //println!("{:?}", four::four_p1());
    //println!("{:?}", one::_one_p1());
    //println!("{:?}", one::_one_p2());
    //println!("{:?}", two::_two_p1());
    //println!("{:?}", two::_two_p2());
    //println!("{:?}", three::_three_p1());
    //println!("{:?}", three::_three_p2());
}